plugins {
    id 'fabric-loom' version '1.7.4'
}

base {
    archivesName = "${project.mod_id}-fabric"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    implementation project(path: ':common', configuration: 'namedElements')
}

loom {
    if (project(':common').file('src/main/resources/velocityhud.accesswidener').exists()) {
        accessWidenerPath = project(':common').file('src/main/resources/velocityhud.accesswidener')
    }
}
