# Mod Information
mod_version=1.0.0
mod_id=velocityhud
mod_name=VelocityHUD
mod_author=GabrielToth
mod_description=Displays real-time velocity on the HUD

# Minecraft Versions
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.22)

# Java
java_version=21

# Fabric
fabric_loader_version=0.16.5
fabric_api_version=0.105.0+1.21.1

# Forge
forge_version=51.0.33
forge_version_range=[51,52)

# Quilt
quilt_loader_version=0.26.4
quilt_fabric_api_version=11.0.0-alpha.3+0.100.7-1.21.1

# NeoForge
neoforge_version=21.1.69
neoforge_version_range=[21,22)

# Dependencies
mixin_version=0.8.5
