plugins {
    id 'net.minecraftforge.gradle' version '[6.0.24,6.2)'
}

base {
    archivesName = "${project.mod_id}-forge"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withSourcesJar()
}

minecraft {
    mappings channel: 'official', version: project.minecraft_version

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'DEBUG'

            mods {
                velocityhud {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'DEBUG'

            mods {
                velocityhud {
                    source sourceSets.main
                }
            }
        }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
    implementation project(path: ':common', configuration: 'namedElements')
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: project.minecraft_version,
            minecraft_version_range: project.minecraft_version_range,
            forge_version: project.forge_version,
            forge_version_range: project.forge_version_range,
            mod_id: project.mod_id,
            mod_name: project.mod_name,
            mod_license: 'MIT',
            mod_version: project.mod_version,
            mod_author: project.mod_author,
            mod_description: project.mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml']) {
        expand replaceProperties
    }
}
