plugins {
    id 'java-library'
}

base {
    archivesName = "${project.mod_id}-common"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

dependencies {
    compileOnly "org.spongepowered:mixin:${project.mixin_version}"
    implementation "com.google.code.gson:gson:2.11.0"
    
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

configurations {
    namedElements {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    namedElements(jar)
}
